/**
 * DebateClaw — two agents argue opposite sides of a controversial statement.
 * An LLM judge reads the full transcript and picks the winner. The "attacker"
 * slot defends the pro / proposition side; the "defender" slot defends the
 * con / opposition side. The win condition is judge-determined, not gameplay
 * mechanical — so DebateClaw is a different shape of game than SecretClaw,
 * which is exactly the point: clawpit isn't a one-mode benchmark.
 *
 * Cost note: the judge IS the leak-detection cost. Unlike SecretClaw (where
 * the default decoder judge is free), DebateClaw requires an LLM judge to
 * deliver a verdict, so every match costs at least one judge call.
 */
import { randomUUID } from "node:crypto";
import { spawn } from "node:child_process";
import Anthropic from "@anthropic-ai/sdk";
import type {
  Agent,
  ChatTurn,
  JudgeVerdict,
  MatchResult,
  MatchUsage,
  SideUsage,
  TokenUsage,
  TranscriptEntry,
  WinReason,
} from "../types.ts";
import { computeCostUsd } from "../cost.ts";

/**
 * 30 controversial statements that are interesting for an AI / tech audience
 * to watch debated. Selection priorities:
 *   - Real disagreement among informed people (not strawmen).
 *   - Falsifiable enough that a confident argument can be made on either side.
 *   - No statements that would put the agent in obvious policy territory
 *     (e.g. instructions for harm). The framing is "what should X policy be"
 *     rather than "how do I do X".
 */
const STATEMENTS = [
  "Large language models should be required to cite their training data.",
  "Open-weight AI models pose a greater long-term risk than closed ones.",
  "Pair programming with an LLM makes mid-level engineers permanently slower at fundamentals.",
  "Code review is more valuable than writing tests.",
  "TypeScript is a net negative for prototype velocity.",
  "Microservices are almost always the wrong choice for teams under 50 engineers.",
  "Remote-only engineering teams produce lower-quality work over a 5-year horizon.",
  "Agentic AI tools will obsolete the IDE within five years.",
  "Static-site generators are strictly better than SPAs for product marketing pages.",
  "Pull-request culture systematically undervalues senior engineers.",
  "Monorepos are worse than polyrepos at organizations larger than 500 engineers.",
  "AI agents should be allowed to autonomously make purchases under $100.",
  "Long-tail open-source maintainers should be paid by the companies that depend on them.",
  "Public benchmarks have done more harm than good to AI progress.",
  "Code generated by LLMs should be required to be marked as such in commits.",
  "Browser-based developer tools have peaked; the next leap is in IDE agents.",
  "Stack-ranking is a defensible performance-management practice for engineering teams.",
  "Frontend frameworks are converging to the point that framework choice no longer matters.",
  "Latency under 100ms is more important than feature completeness for AI products.",
  "Designers should learn to code; engineers should not need to learn design.",
  "On-call rotations are an unethical labor practice in their current form.",
  "Most software companies should not employ a 'platform team'.",
  "Continuous deployment is an anti-pattern outside of consumer SaaS.",
  "Standardized coding interviews remain the least-bad hiring signal.",
  "End-to-end tests should be the smallest layer of any test pyramid.",
  "Reading code is a more developable skill than writing code.",
  "Open-source licenses should be required to ban training on the code.",
  "Most engineering teams over-invest in observability.",
  "Software engineers without a CS degree are at a permanent ceiling in systems work.",
  "Comments in code are evidence that the code itself is not clear enough.",
];

export function pickStatement(seed?: number): string {
  const idx =
    typeof seed === "number"
      ? Math.abs(seed) % STATEMENTS.length
      : Math.floor(Math.random() * STATEMENTS.length);
  return STATEMENTS[idx]!;
}

const PRO_SYSTEM = (statement: string, maxTurns: number) =>
  `You are the PRO side of a structured debate.

Statement: "${statement}"
Your position: argue strongly that this statement is TRUE.

Format rules:
- ${maxTurns} turns each side, alternating. You speak first each round.
- Each turn ≤ 5 sentences. Direct argument, no hedging "well, it depends" preambles.
- Address your opponent's strongest counter-argument when you have one.
- Concede minor points when it sharpens your overall case; never concede the main claim.
- Don't break character to discuss the debate format itself.

A judge will pick a winner based on argument strength, not on which position they personally favour.`;

const CON_SYSTEM = (statement: string, maxTurns: number) =>
  `You are the CON side of a structured debate.

Statement: "${statement}"
Your position: argue strongly that this statement is FALSE.

Format rules:
- ${maxTurns} turns each side, alternating. PRO speaks first; you respond.
- Each turn ≤ 5 sentences. Direct argument, no hedging "well, it depends" preambles.
- Address your opponent's strongest argument when you have one.
- Concede minor points when it sharpens your overall case; never concede the main claim.
- Don't break character to discuss the debate format itself.

A judge will pick a winner based on argument strength, not on which position they personally favour.`;

const DEFAULT_JUDGE_MODEL = "claude-haiku-4-5-20251001";

interface DebateJudgement {
  winner: "pro" | "con";
  reasoning: string;
  usage?: TokenUsage;
  note?: string;
}

function buildJudgePrompt(
  statement: string,
  transcript: TranscriptEntry[],
): string {
  const proTurns = transcript.filter((t) => t.role === "attacker");
  const conTurns = transcript.filter((t) => t.role === "defender");
  const renderSide = (label: string, turns: TranscriptEntry[]) =>
    turns.map((t, i) => `${label} turn ${i + 1}: ${t.content.trim()}`).join("\n\n");
  return `Statement under debate: "${statement}"

Two sides argued. Read both sides in full.

PRO side (arguing the statement is TRUE):
${renderSide("PRO", proTurns)}

CON side (arguing the statement is FALSE):
${renderSide("CON", conTurns)}

Your job: decide which side made the stronger case. You must:
- Judge argument quality (rigor, specificity, response to counter-points), not whether you personally agree with the statement.
- If both sides are roughly equal, lean toward the side that ENGAGED MORE DIRECTLY with the opponent's strongest point.
- Avoid "both have merit" non-answers — you must pick.

Reply with one JSON object and nothing else:
{ "winner": "pro" | "con", "reasoning": "two-to-four sentences explaining the call" }`;
}

function parseJudgeReply(raw: string, modelId: string): DebateJudgement {
  const m = raw.match(/\{[\s\S]*\}/);
  if (!m) {
    return {
      winner: "pro",
      reasoning: `judge returned no JSON: ${raw.slice(0, 200)}`,
      note: "parse-error",
    };
  }
  try {
    const parsed = JSON.parse(m[0]);
    const winner = parsed.winner === "con" ? "con" : "pro";
    const reasoning = String(parsed.reasoning ?? "").slice(0, 800);
    return { winner, reasoning };
  } catch (err: any) {
    return {
      winner: "pro",
      reasoning: `judge JSON parse failed: ${err?.message ?? "unknown"}`,
      note: "parse-error",
    };
  }
}

/**
 * Run the judge via the local `claude` CLI (subscription-backed) when no
 * ANTHROPIC_API_KEY is set. Mirrors the cc:* agent pattern: spawn the CLI
 * with the same context-disabling flags so the cost stays close to a direct
 * API call. Returns a `cli-error` note on failure so the caller can fall
 * back gracefully.
 */
async function judgeViaCli(
  statement: string,
  transcript: TranscriptEntry[],
  modelId: string,
): Promise<DebateJudgement> {
  const prompt = buildJudgePrompt(statement, transcript);
  const system =
    "You are a strict debate judge. You reply with exactly one JSON object and no commentary outside of it.";
  const args = [
    "-p", prompt,
    "--model", modelId,
    "--output-format", "json",
    "--tools", "",
    "--system-prompt", system,
    "--strict-mcp-config",
    "--mcp-config", '{"mcpServers":{}}',
    "--setting-sources", "",
    "--disable-slash-commands",
    "--no-session-persistence",
  ];
  return new Promise((resolve) => {
    const proc = spawn("claude", args, {
      env: { ...process.env, CI: "1" },
      stdio: ["ignore", "pipe", "pipe"],
    });
    let stdout = "";
    const timer = setTimeout(() => {
      proc.kill("SIGTERM");
      resolve({
        winner: "pro",
        reasoning: "judge CLI timed out (60s)",
        note: "cli-error",
      });
    }, 60_000);
    proc.stdout.on("data", (c) => (stdout += c.toString("utf8")));
    proc.on("close", () => {
      clearTimeout(timer);
      const jsonStart = stdout.indexOf("{");
      if (jsonStart < 0) {
        resolve({
          winner: "pro",
          reasoning: "judge CLI returned no JSON",
          note: "cli-error",
        });
        return;
      }
      try {
        const cliResult = JSON.parse(stdout.slice(jsonStart)) as {
          result?: string;
          is_error?: boolean;
          usage?: {
            input_tokens?: number;
            output_tokens?: number;
          };
        };
        const usage = {
          model: modelId,
          inputTokens: cliResult.usage?.input_tokens ?? 0,
          outputTokens: cliResult.usage?.output_tokens ?? 0,
        };
        if (cliResult.is_error || !cliResult.result) {
          resolve({
            winner: "pro",
            reasoning: `judge CLI is_error: ${(cliResult.result ?? "no message").slice(0, 200)}`,
            note: "cli-error",
            usage,
          });
          return;
        }
        const parsed = parseJudgeReply(cliResult.result, modelId);
        resolve({ ...parsed, usage });
      } catch (err: any) {
        resolve({
          winner: "pro",
          reasoning: `judge CLI parse failed: ${err?.message ?? "unknown"}`,
          note: "cli-error",
        });
      }
    });
  });
}

/**
 * Hidden judge call. Reads the full transcript and decides who made the
 * stronger case. The judge is told explicitly NOT to be swayed by which
 * position aligns with its own opinions. Routes to API when
 * ANTHROPIC_API_KEY is set, otherwise to the `claude` CLI subprocess so the
 * Max subscription quota covers it.
 */
async function judgeDebate(
  statement: string,
  transcript: TranscriptEntry[],
  modelId: string,
): Promise<DebateJudgement> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    // No API key — try the local Claude CLI (Max subscription). This is the
    // common path for hobbyist demos.
    return judgeViaCli(statement, transcript, modelId);
  }
  const client = new Anthropic({ apiKey });
  const prompt = buildJudgePrompt(statement, transcript);
  try {
    const res = await client.messages.create({
      model: modelId,
      system:
        "You are a strict debate judge. You reply with exactly one JSON object and no commentary outside of it.",
      messages: [{ role: "user", content: prompt }],
      max_tokens: 320,
      temperature: 0,
    });
    const raw = res.content
      .filter((b): b is Anthropic.TextBlock => b.type === "text")
      .map((b) => b.text)
      .join("\n")
      .trim();
    const parsed = parseJudgeReply(raw, modelId);
    return {
      ...parsed,
      usage: {
        model: modelId,
        inputTokens: res.usage?.input_tokens ?? 0,
        outputTokens: res.usage?.output_tokens ?? 0,
      },
    };
  } catch (err: any) {
    return {
      winner: "pro",
      reasoning: `judge API error: ${err?.message ?? String(err)}`,
      note: "api-error",
    };
  }
}

export interface DebateClawOptions {
  maxTurns?: number;
  seed?: number;
  maxTokens?: number;
  onTurn?: (entry: TranscriptEntry) => void;
  /** Override the judge model. Default: claude-haiku-4-5-20251001 (cheap, fast). */
  judgeModel?: string;
  matchId?: string;
}

function emptySide(): SideUsage {
  return { inputTokens: 0, outputTokens: 0, costUsd: 0 };
}

function addUsage(side: SideUsage, usage: TokenUsage | undefined) {
  if (!usage) return;
  side.inputTokens += usage.inputTokens;
  side.outputTokens += usage.outputTokens;
  side.costUsd += computeCostUsd(
    usage.model,
    usage.inputTokens,
    usage.outputTokens,
  );
}

export async function runDebateClaw(
  attacker: Agent, // PRO side
  defender: Agent, // CON side
  opts: DebateClawOptions = {},
): Promise<MatchResult> {
  const maxTurns = opts.maxTurns ?? 3;
  const judgeModel = opts.judgeModel ?? DEFAULT_JUDGE_MODEL;
  const statement = pickStatement(opts.seed);

  const proSystem = PRO_SYSTEM(statement, maxTurns);
  const conSystem = CON_SYSTEM(statement, maxTurns);

  const proHistory: ChatTurn[] = [
    {
      role: "user",
      content: `Open the debate. State your strongest case for: "${statement}"`,
    },
  ];
  const conHistory: ChatTurn[] = [];

  const transcript: TranscriptEntry[] = [];
  const startedAt = new Date();
  const startMs = Date.now();
  const attackerUsage = emptySide();
  const defenderUsage = emptySide();
  const judgeUsage = emptySide();

  let winner: "attacker" | "defender" = "attacker";
  let reason: WinReason = "judge_decision";
  let turnsPlayed = 0;
  let agentErrored = false;

  for (let turn = 1; turn <= maxTurns; turn++) {
    // PRO turn
    let proMsg: string;
    try {
      const res = await attacker.call({
        systemPrompt: proSystem,
        history: proHistory,
        maxTokens: opts.maxTokens,
      });
      proMsg = res.text;
      addUsage(attackerUsage, res.usage);
    } catch (err: any) {
      reason = "attacker_error";
      winner = "defender";
      transcript.push({
        turn,
        role: "attacker",
        content: `[error: ${err?.message ?? String(err)}]`,
        ts: Date.now(),
      });
      turnsPlayed = turn;
      agentErrored = true;
      break;
    }
    proHistory.push({ role: "assistant", content: proMsg });
    conHistory.push({ role: "user", content: proMsg });
    const proEntry: TranscriptEntry = {
      turn,
      role: "attacker",
      content: proMsg,
      ts: Date.now(),
    };
    transcript.push(proEntry);
    opts.onTurn?.(proEntry);

    // CON turn
    let conMsg: string;
    try {
      const res = await defender.call({
        systemPrompt: conSystem,
        history: conHistory,
        maxTokens: opts.maxTokens,
      });
      conMsg = res.text;
      addUsage(defenderUsage, res.usage);
    } catch (err: any) {
      reason = "defender_error";
      winner = "attacker";
      transcript.push({
        turn,
        role: "defender",
        content: `[error: ${err?.message ?? String(err)}]`,
        ts: Date.now(),
      });
      turnsPlayed = turn;
      agentErrored = true;
      break;
    }
    conHistory.push({ role: "assistant", content: conMsg });
    proHistory.push({ role: "user", content: conMsg });
    const conEntry: TranscriptEntry = {
      turn,
      role: "defender",
      content: conMsg,
      ts: Date.now(),
    };
    transcript.push(conEntry);
    opts.onTurn?.(conEntry);
    turnsPlayed = turn;
  }

  let verdict: JudgeVerdict | undefined;
  if (!agentErrored) {
    const result = await judgeDebate(statement, transcript, judgeModel);
    winner = result.winner === "pro" ? "attacker" : "defender";
    reason = "judge_decision";
    addUsage(judgeUsage, result.usage);
    verdict = {
      leaked: false, // not applicable for debates
      evidence: result.reasoning,
      model: judgeModel,
      stage: "end_of_match",
      note: result.note,
      usage: result.usage,
    };
  }

  const usage: MatchUsage = {
    attacker: attackerUsage,
    defender: defenderUsage,
    judge: judgeUsage,
    totalCostUsd:
      attackerUsage.costUsd + defenderUsage.costUsd + judgeUsage.costUsd,
  };

  const endedAt = new Date();
  return {
    id: opts.matchId ?? randomUUID(),
    game: "debate-claw",
    attacker: { id: attacker.id, label: attacker.label },
    defender: { id: defender.id, label: defender.label },
    secret: "",            // unused in DebateClaw
    topic: statement,      // the full statement under debate
    winner,
    reason,
    leakDetector: "none",
    judgeVerdict: verdict,
    turns: turnsPlayed,
    maxTurns,
    transcript,
    usage,
    startedAt: startedAt.toISOString(),
    endedAt: endedAt.toISOString(),
    durationMs: Date.now() - startMs,
  };
}
